### ISSUE TITLE
TODO / Wishlist

### ISSUE THREAD

**Issue by Flydiverny** [Flydiverny/app-portal#1]
**Features**
- [x] Download counter
- [ ] Version regex
- [ ] Email new release/subscribe
- [x] Show download endpoint somwhere(?) ie `http://hostname/download/`

**Upload improvements:**
- [ ] Post endpoints by app key(?) (skip parsing of apk name)
  - [ ] Support mapping, changelog, version
- [ ] ~~Allow selection of app when manually uploading~~
- [x] Allow selection of dependency when manually uploading
- [x] Add changelog when manually uploading

**Low prio**
- [ ] Token handling/generating instead of config file
- [ ] ~~Material design and icons instead of bootstrap and glyphicons~~
- [x] Non cdn version of bootstrap ?

**Other**
- [x] Hidden - > Listed,
- [ ] Delete option 
- [x] Released flag (no download if not) 
- [x] Metadata page (return version,  download URL, compatible list, other things?) 
- [ ] Makefile for Debian package?  Because why not 
- [x] Upgrade dependencies, jade to pug for one 
- [x] Redirect to edit page for version if only uploading one apk 
- [ ] Delete files not uploaded properly... 
- [ ] Meta / stats page show total downloads or so 
- [x] /download/ could list all releases? That are listed, for all apps, though that will be a long list so eh paging I guess. Possibly simplified without showing compatibility to improve response time 
- [ ] First setup / config generation
- [ ] logo & favicon upload.
- [ ] default logo
